### ISSUE TITLE
Ability to see api call's result for non-admin users

### ISSUE THREAD

**Issue by eiser82** [eiser82/bookhub#4]
Scenario: Perform a search as a non admin
   Given I am in the root page
   And I am logged in as a non-admin user
   When I fill in search with "ruby" 
   And I click on the submit button
   Then I should see a results page with "ruby" listed

**Comment by jmaya** [comment]
Given I am in the root page
And I am logged in as a non-admin user
When I fill in search with "ruby" 
And I click on the submit button
Then I should see a results page with "ruby" listed

**Comment by eiser82** [comment]
thanks @jmaya
